name: Synthesize CDK stacks

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  github-username:
    description: 'GitHub username for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    # Set up Consent Management API artifacts
    - name: Checkout Consent Management API repository
      uses: actions/checkout@v4
      with:
        repository: 'Consent-Management-Platform/consent-management-api'
        path: 'consent-management-api'
    - name: Run Build Consent API action
      uses: ./consent-management-api/.github/actions/buildConsentApi/
      with:
        github-token: ${{ inputs.github-token }}
        github-username: ${{ inputs.github-username }}

    # Set up Consent Expiry Processor artifacts
    - name: Checkout Consent Expiry Processor repository
      uses: actions/checkout@v4
      with:
        repository: 'Consent-Management-Platform/consent-expiry-processor'
        path: 'consent-expiry-processor'
    - name: Run Build Consent Expiry Processor action
      uses: ./consent-expiry-processor/.github/actions/buildAndTest/
      with:
        github-token: ${{ inputs.github-token }}
        github-username: ${{ inputs.github-username }}

    # Set up Consent History API artifacts
    - name: Checkout Consent History API repository
      uses: actions/checkout@v4
      with:
        repository: 'Consent-Management-Platform/consent-history-api'
        path: 'consent-history-api'
    - name: Run Build Consent History API action
      uses: ./consent-history-api/.github/actions/buildApi/
      with:
        github-token: ${{ inputs.github-token }}
        github-username: ${{ inputs.github-username }}

    # Set up Consent History Ingestor artifacts
    - name: Checkout Consent History Ingestor repository
      uses: actions/checkout@v4
      with:
        repository: 'Consent-Management-Platform/consent-history-ingestor'
        path: 'consent-history-ingestor'
    - name: Run Build Consent History Ingestor action
      uses: ./consent-history-ingestor/.github/actions/buildIngestor/
      with:
        github-token: ${{ inputs.github-token }}
        github-username: ${{ inputs.github-username }}

    # Build CDK package and synthesize stacks
    - name: Checkout CDK package
      uses: actions/checkout@v4
      with:
        repository: 'Consent-Management-Platform/consent-management-api-cdk'
        path: 'consent-management-api-cdk'
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        npm install
        npm install -g typescript
        npm install -g aws-cdk
        cdk --version
        aws --version
      shell: bash
      working-directory: consent-management-api-cdk
    - name: Validate dependency artifacts present
      run: |
        ls -l ../consent-management-api/build/distributions
        ls -l ../consent-management-api/build/distributions/consent-management-api.zip
        ls -l ../consent-history-api/build/distributions
        ls -l ../consent-history-api/build/distributions/consent-history-api.zip
        ls -l ../consent-history-ingestor/build/distributions
        ls -l ../consent-history-ingestor/build/distributions/consent-history-ingestor.zip
      shell: bash
      working-directory: consent-management-api-cdk
    - name: Build CDK package and run tests
      run: npm test
      shell: bash
      working-directory: consent-management-api-cdk
    - name: Synthesize CDK stacks
      run: npx cdk synth
      shell: bash
      working-directory: consent-management-api-cdk
    - name: Validate CDK outputs present
      run: ls -l cdk.out/*.json
      shell: bash
      working-directory: consent-management-api-cdk
