# This GitHub Workflow will deploy code and infrastructure changes to the provided AWS account
#
# Prerequisites:
# - Manually deployed CodePipelineStack to AWS at least once
name: Deploy
on:
  # Enable running workflow manually from GitHub Actions
  workflow_dispatch:
    # Require AWS credentials and region to be provided
    inputs:
      AWS_ACCOUNT_ID:
        description: AWS account to deploy to
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: consent-management-api-cdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and synthesize stacks
        uses: ./.github/actions/synthesizeStacks
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: ${{ github.actor }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ github.event.inputs.AWS_ACCOUNT_ID }}:role/github-ci-role
          aws-region: us-west-2
      - name: Deploy CDK bootstrap stack
        run: npx cdk bootstrap --require-approval never
      - name: Deploy CDK stacks
        run: |
          npx cdk deploy CodePipelineStack --require-approval never && \
          npx cdk deploy ConsentDataStack --require-approval never && \
          npx cdk deploy ConsentHistoryDataStack --require-approval never
