# This GitHub Workflow will generate API clients for the AWS Gateway based API services
#
# Prerequisites:
# 1. Have deployed the CDK stacks for the API services
name: Generate API Clients
on:
  # Enable running workflow manually from GitHub Actions
  workflow_dispatch:
    inputs:
      AWS_ACCOUNT_ID:
        description: AWS account of API services
        required: true
      AWS_REGION:
        description: AWS region of API services
        required: true
      API_STAGE_NAME:
        description: API Gateway stage name
        required: true

jobs:
  generate-api-clients:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ github.event.inputs.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ github.event.inputs.AWS_ACCOUNT_ID }}:role/github-ci-role
      - name: Retrieve API Gateway ID for the Consent Management API
        id: get-consent-management-api-gateway-id
        run: |
          apiGatewayId=$(aws cloudformation list-exports \
            --region ${{ github.event.inputs.AWS_REGION }} \
            --query "Exports[?Name == 'ConsentManagementApiGatewayId'].Value" \
            | jq .[0])
          echo "CONSENT_MANAGEMENT_API_GATEWAY_ID=${apiGatewayId}" >> "$GITHUB_OUTPUT"
      - name: Query Consent Management API Gateway for Java client SDK
        run: |
          aws apigateway get-sdk \
            --region ${{ github.event.inputs.AWS_REGION }} \
            --rest-api-id ${{ steps.get-consent-management-api-gateway-id.outputs.CONSENT_MANAGEMENT_API_GATEWAY_ID }} \
            --stage-name ${{ github.event.inputs.API_STAGE_NAME }} \
            --sdk-type java \
            --parameters service.name=ConsentManagementApi,java.package-name='com.consentframework.consentmanagement.sdk',java.build-system='gradle',java.group-id='com.consentframework',java.artifact-id='consent-management-api-java-sdk',java.artifact-version='0.0.1' \
            consent-management-api-java-client.zip
      - name: Archive Java client SDK zip file
        uses: actions/upload-artifact@v4
        with:
          name: consent-management-api-java-client
          path: consent-management-api-java-client.zip
