# This GitHub Workflow will run basic AWS CLI based integ tests
# against the provided AWS account to validate API functionality
# continues to work as expected after deployments.
#
# Prerequisites:
# 1. Deploy CDK stacks to the provided AWS account.
# 2. Set up AWS CLI and local AWS credentials.
name: API Integ Tests
on:
  # Enable running workflow manually from GitHub Actions
  workflow_dispatch:
    # Require AWS account ID and region to be provided
    inputs:
      AWS_ACCOUNT_ID:
        description: AWS account to deploy to
        required: true
      AWS_REGION:
        description: AWS region to deploy to
        required: true

jobs:
  run-integ-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Consent Management API integ tests
        uses: ./.github/actions/consentManagementIntegTests
        with:
          aws-account-id: ${{ github.event.inputs.AWS_ACCOUNT_ID }}
          aws-region: ${{ github.event.inputs.AWS_REGION }}
