# This GitHub workflow will automatically build and test code changes
name: Build
on:
  # Run automatically when pushing code or config changes
  push:
    paths:
      - '**.json'
      - '**.ts'
      - '**.ts.snap'
      - '**.yml'
  # Run automatically for all pull requests
  pull_request:
  # Enable running as a subset of another GitHub Workflow
  workflow_call:
  # Enable running workflow manually from GitHub Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: consent-management-api-cdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and synthesize stacks
        uses: ./.github/actions/synthesizeStacks
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: ${{ github.actor }}
